import Head from 'next/head'
import { Inter } from 'next/font/google'
import HomePage from './homepage/HomePage'
import { Navbar } from '@/components/Navbar'
  
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>MattGomb&apos;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className='bg-dark'>
        <Navbar />
        <HomePage />
      </main>
    </>
  )
}
